---
title: "Trump Approval Ratings"
author: "Y.L"
date: "2020-10-22"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---



<div id="trumps-approval-margins" class="section level1">
<h1>Trump’s Approval Margins</h1>
<p>As we saw in class, fivethirtyeight.com has detailed data on <a href="https://projects.fivethirtyeight.com/trump-approval-ratings">all polls that track the president’s approval</a></p>
<pre class="r"><code>approval_polllist &lt;- read_csv(here::here(&#39;data&#39;, &#39;approval_polllist.csv&#39;))

approval_polllist$enddate &lt;- mdy(approval_polllist$enddate)
glimpse(approval_polllist)</code></pre>
<pre><code>## Rows: 15,619
## Columns: 22
## $ president           &lt;chr&gt; &quot;Donald Trump&quot;, &quot;Donald Trump&quot;, &quot;Donald Trump&quot;,...
## $ subgroup            &lt;chr&gt; &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;, &quot;All pol...
## $ modeldate           &lt;chr&gt; &quot;9/27/2020&quot;, &quot;9/27/2020&quot;, &quot;9/27/2020&quot;, &quot;9/27/20...
## $ startdate           &lt;chr&gt; &quot;1/20/2017&quot;, &quot;1/20/2017&quot;, &quot;1/20/2017&quot;, &quot;1/21/20...
## $ enddate             &lt;date&gt; 2017-01-22, 2017-01-22, 2017-01-24, 2017-01-23...
## $ pollster            &lt;chr&gt; &quot;Gallup&quot;, &quot;Morning Consult&quot;, &quot;Ipsos&quot;, &quot;Gallup&quot;,...
## $ grade               &lt;chr&gt; &quot;B&quot;, &quot;B/C&quot;, &quot;B-&quot;, &quot;B&quot;, &quot;B-&quot;, &quot;C+&quot;, &quot;B+&quot;, &quot;B&quot;, &quot;...
## $ samplesize          &lt;dbl&gt; 1500, 1992, 1632, 1500, 1651, 1500, 1190, 1500,...
## $ population          &lt;chr&gt; &quot;a&quot;, &quot;rv&quot;, &quot;a&quot;, &quot;a&quot;, &quot;a&quot;, &quot;lv&quot;, &quot;rv&quot;, &quot;a&quot;, &quot;lv&quot;...
## $ weight              &lt;dbl&gt; 0.262, 0.680, 0.153, 0.243, 0.142, 0.200, 1.514...
## $ influence           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ approve             &lt;dbl&gt; 45.0, 46.0, 42.1, 45.0, 42.3, 57.0, 36.0, 46.0,...
## $ disapprove          &lt;dbl&gt; 45.0, 37.0, 45.2, 46.0, 45.8, 43.0, 44.0, 45.0,...
## $ adjusted_approve    &lt;dbl&gt; 45.7, 45.3, 43.2, 45.7, 43.4, 51.5, 37.6, 46.7,...
## $ adjusted_disapprove &lt;dbl&gt; 43.6, 38.3, 43.9, 44.6, 44.5, 44.5, 42.8, 43.6,...
## $ multiversions       &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,...
## $ tracking            &lt;lgl&gt; TRUE, NA, TRUE, TRUE, TRUE, TRUE, NA, TRUE, TRU...
## $ url                 &lt;chr&gt; &quot;http://www.gallup.com/poll/201617/gallup-daily...
## $ poll_id             &lt;dbl&gt; 49253, 49249, 49426, 49262, 49425, 49266, 49260...
## $ question_id         &lt;dbl&gt; 77265, 77261, 77599, 77274, 77598, 77278, 77272...
## $ createddate         &lt;chr&gt; &quot;1/23/2017&quot;, &quot;1/23/2017&quot;, &quot;3/1/2017&quot;, &quot;1/24/201...
## $ timestamp           &lt;chr&gt; &quot;00:45:20 27 Sep 2020&quot;, &quot;00:45:20 27 Sep 2020&quot;,...</code></pre>
<div id="create-a-plot" class="section level2">
<h2>Create a plot</h2>
<p>What I would like you to do is to calculate the average net approval rate (approve- disapprove) for each week since he got into office. I want you plot the net approval, along with its 95% confidence interval. There are various dates given for each poll, please use <code>enddate</code>, i.e., the date the poll ended.</p>
<pre class="r"><code>approval_polllist$week_number &lt;- week(approval_polllist$enddate)
approval_polllist$net_approve &lt;- approval_polllist$approve - approval_polllist$disapprove
approval_polllist_summary &lt;- summarySE(approval_polllist, measurevar=&quot;net_approve&quot;, groupvars=&quot;week_number&quot;)
ggplot(approval_polllist_summary, aes(x=week_number, y=net_approve)) + geom_bar(position=position_dodge(), stat = &quot;identity&quot;) + geom_errorbar(aes(ymin=net_approve-ci, ymax=net_approve+ci), width=.2, position=position_dodge(.9))</code></pre>
<p><img src="/Projects/Project 2/Project2.index_files/figure-html/unnamed-chunk-2-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>You can facet by year, and add an orange line at zero. Your plot should look like this:</p>
<p><img src="C:/Users/sophi/OneDrive/Desktop/my_website_2/images/trump_approval_margin.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="compare-confidence-intervals" class="section level2">
<h2>Compare Confidence Intervals</h2>
<p>Compare the confidence intervals for <code>week 15</code> (6-12 April 2020) and <code>week 34</code> (17-23 August 2020). Can you explain what’s going on? One paragraph would be enough.</p>
<pre class="r"><code>week_15_vs_week_34 &lt;- approval_polllist %&gt;% filter(week_number==15|week_number==34) 
glimpse(week_15_vs_week_34)</code></pre>
<pre><code>## Rows: 672
## Columns: 24
## $ president           &lt;chr&gt; &quot;Donald Trump&quot;, &quot;Donald Trump&quot;, &quot;Donald Trump&quot;,...
## $ subgroup            &lt;chr&gt; &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;, &quot;All pol...
## $ modeldate           &lt;chr&gt; &quot;9/27/2020&quot;, &quot;9/27/2020&quot;, &quot;9/27/2020&quot;, &quot;9/27/20...
## $ startdate           &lt;chr&gt; &quot;4/5/2017&quot;, &quot;4/5/2017&quot;, &quot;4/6/2017&quot;, &quot;4/5/2017&quot;,...
## $ enddate             &lt;date&gt; 2017-04-09, 2017-04-09, 2017-04-09, 2017-04-11...
## $ pollster            &lt;chr&gt; &quot;Ipsos&quot;, &quot;Rasmussen Reports/Pulse Opinion Resea...
## $ grade               &lt;chr&gt; &quot;B-&quot;, &quot;C+&quot;, &quot;B/C&quot;, &quot;B/C&quot;, &quot;B-&quot;, &quot;B&quot;, &quot;C+&quot;, &quot;A&quot;,...
## $ samplesize          &lt;dbl&gt; 1683, 1500, 1988, 1501, 1634, 1500, 1500, 1006,...
## $ population          &lt;chr&gt; &quot;a&quot;, &quot;lv&quot;, &quot;rv&quot;, &quot;a&quot;, &quot;a&quot;, &quot;a&quot;, &quot;lv&quot;, &quot;a&quot;, &quot;a&quot;,...
## $ weight              &lt;dbl&gt; 0.1021, 0.0733, 0.5285, 0.5565, 0.0991, 0.1622,...
## $ influence           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ approve             &lt;dbl&gt; 46.5, 44.0, 48.0, 39.0, 48.0, 40.0, 47.0, 43.0,...
## $ disapprove          &lt;dbl&gt; 47.8, 56.0, 47.0, 54.0, 46.3, 53.0, 53.0, 49.0,...
## $ adjusted_approve    &lt;dbl&gt; 47.6, 38.5, 47.3, 40.9, 49.1, 40.7, 41.5, 44.3,...
## $ adjusted_disapprove &lt;dbl&gt; 46.5, 57.5, 48.3, 50.7, 45.0, 51.6, 54.5, 48.5,...
## $ multiversions       &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,...
## $ tracking            &lt;lgl&gt; TRUE, TRUE, NA, NA, TRUE, TRUE, TRUE, NA, NA, T...
## $ url                 &lt;chr&gt; &quot;http://polling.reuters.com/#poll/CP3_2/&quot;, &quot;htt...
## $ poll_id             &lt;dbl&gt; 49599, 49593, 49603, 49620, 49598, 49595, 49596...
## $ question_id         &lt;dbl&gt; 77871, 77861, 77879, 77904, 77870, 77863, 77864...
## $ createddate         &lt;chr&gt; &quot;4/11/2017&quot;, &quot;4/10/2017&quot;, &quot;4/12/2017&quot;, &quot;4/17/20...
## $ timestamp           &lt;chr&gt; &quot;00:45:20 27 Sep 2020&quot;, &quot;00:45:20 27 Sep 2020&quot;,...
## $ week_number         &lt;dbl&gt; 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,...
## $ net_approve         &lt;dbl&gt; -1.3, -12.0, 1.0, -15.0, 1.7, -13.0, -6.0, -6.0...</code></pre>
<pre class="r"><code>summarySE(week_15_vs_week_34, measurevar=&quot;net_approve&quot;, groupvars=&quot;week_number&quot;)</code></pre>
<pre><code>##   week_number   N net_approve   sd    se    ci
## 1          15 321       -8.82 5.71 0.319 0.627
## 2          34 351      -13.15 7.05 0.376 0.740</code></pre>
<p>According to the data frame, the net approval went from -8.82 to -13.15 from week 15 to week 34, signifying that there has been a significant rise on disapproval on Trump administration. The declining net approval rate in week 34 can be linked to a series of social events and controversial Trump policies on covid, including authorising Plasma treatment amid attacks on FDA, uncontrollable California wildfire, the Louisiana shooting - another police killing of Black man which sparked local outrage and rising protests.</p>
</div>
</div>
